### ISSUE TITLE
ssl certificate issues

### ISSUE THREAD

**Issue by alcohol** [baptistedonaux/docker-hhvm#1]
This was the only docker image I could find so far that offered the latest version of hhvm. Unfortunately, while trying to run a `file_get_contents` against a https url, I ran into "SSL certificate problem: unable to get local issuer certificate". Seems like ca-certificates package is not installed properly/outdated? Is the jessie base image you are using up to date?

**Comment by baptistedonaux** [comment]
Hi, thank you for your feedback. Do you have a solution or a snippet to reproduce this fail.

**Comment by alcohol** [comment]
Well, I was trying to run this while trying to debug an issue for a Composer user:

```
docker run -it --rm --name segfault-issue baptistedonaux/hhvm hhvm --php -r 'var_dump(json_decode(file_get_contents("https://dump.robbast.nl/segfault.json"), true));'
```

but it returns

```
Warning: Failed to open https://dump.robbast.nl/segfault.json (SSL certificate problem: unable to get local issuer certificate) in /tmp/php-wrap-DxdeTC on line 2
NULL
```

**Comment by baptistedonaux** [comment]
Fixed! Images currently under construction.

**Comment by alcohol** [comment]
Thanks :-)

**Comment by baptistedonaux** [comment]
Done ! Thank you for your feedback

**Comment by alcohol** [comment]
Can confirm that it works as expected now. Thanks for the quick action.
