### ISSUE TITLE
Problem reading ini settings.

### ISSUE THREAD

**Issue by mikaelmattsson** [baptistedonaux/docker-hhvm#2]
I can't seem to get my custom ini settings to be loaded.

Dockerfile:

    FROM baptistedonaux/hhvm:3.15

    COPY server.ini /etc/hhvm/server.ini

It works if i set them like this:

    CMD ["hhvm", "-m", "server", "-vServer.Type=fastcgi", "-dhhvm.server.port=9000", "-dhhvm.log.use_log_file=true", "-dhhvm.log.file=/var/log/hhvm/error.log", "-dhhvm.debug.server_error_message=true", "-dhhvm.log.level=Info", "-dhhvm.log.use_request_log=true", "-dxdebug.enable=1", "-dxdebug.remote_enable=1", "-dxdebug.remote_autostart=1", "-dxdebug.idekey=docker", "-dxdebug.remote_host=172.16.123.1", "-dxdebug.remote_port=9000", "-dxdebug.remote_mode=req", "-dxdebug.remote_connect_back=0", "-dhhvm.debugger.enable_debugger=true", "-dhhvm.debugger.enable_debugger_server=true", "--debug-sandbox=default"]

**Comment by baptistedonaux** [comment]
Do you have try with ```-c```argument ?

```
FROM baptistedonaux/hhvm:3.15

COPY server.ini /etc/hhvm/server.ini

CMD ["-c", "/etc/hhvm/server.ini"]
```

**Comment by mikaelmattsson** [comment]
Seem to work. This will do just fine. Thanks!
